local ScriptBuilder = {}

local function header(toolName, sourceRepositoryUrl)
    return ("-- Generated by Hydroxide's %s: %s\n\n"):format(toolName, sourceRepositoryUrl)
end

function ScriptBuilder.HelperLoader(options, moduleNames)
    local serializedNames = {}
    for _index, name in ipairs(moduleNames or {}) do
        table.insert(serializedNames, ("%q"):format(name))
    end
    local modules = "{ " .. table.concat(serializedNames, ", ") .. " }"

    if options.LocalRoot then
        local loaderPath = options.LocalRoot .. "/modules/Helpers.lua"
        return ([[local Helpers = loadstring(readfile(%q), "modules/Helpers.lua")()
local oh = Helpers.load({
    localRoot = %q,
    modules = %s,
    constants = {
        sourceMode = "local",
        sourceRepositoryUrl = %q,
    },
})

]]):format(loaderPath, options.LocalRoot, modules, options.SourceRepositoryUrl)
    end

    local loaderUrl = options.SourceBaseUrl .. "modules/Helpers.lua"
    return ([[local Helpers = loadstring(game:HttpGetAsync(%q), "modules/Helpers.lua")()
local oh = Helpers.load({
    sourceBaseUrl = %q,
    modules = %s,
    constants = {
        sourceMode = "web",
        sourceRepositoryUrl = %q,
    },
})

]]):format(loaderUrl, options.SourceBaseUrl, modules, options.SourceRepositoryUrl)
end

function ScriptBuilder.RemoteCall(options)
    local arguments = options.Arguments or {}
    local declarations = {}
    local argumentNames = {}

    for index, argument in ipairs(arguments) do
        local name = ("oh%s%d"):format(argument.TypeName, index)
        table.insert(declarations, ("local %s = %s"):format(name, argument.Value))
        table.insert(argumentNames, name)
    end

    local script = header("RemoteSpy", options.SourceRepositoryUrl)
    if #declarations > 0 then
        script = script .. table.concat(declarations, "\n") .. "\n\n"
    end

    return script
        .. options.RemotePath
        .. ":"
        .. options.Method
        .. "("
        .. table.concat(argumentNames, ", ")
        .. ")"
end

function ScriptBuilder.UpvalueMutation(options)
    local script = header("Upvalue Scanner", options.SourceRepositoryUrl)
        .. ScriptBuilder.HelperLoader(options, { "closure" })
        .. ([[local closureTools = oh.closure
local scriptPath = %s
local closureName = "%s"
local upvalueIndex = %d
local closureConstants = %s

local closure = closureTools.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = YOUR_NEW_VALUE_HERE
]]):format(
            options.ScriptPath,
            options.ClosureName,
            options.UpvalueIndex,
            options.ClosureConstants
        )

    if options.ElementIndex and options.ElementIndex ~= "nil" then
        script = script .. ("local elementIndex = %s\n"):format(options.ElementIndex)
        return script
            .. "\n\n-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS\n"
            .. "debug.getupvalue(closure, upvalueIndex)[elementIndex] = value"
    end

    return script
        .. "\n\n-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS\n"
        .. "debug.setupvalue(closure, upvalueIndex, value)"
end

return ScriptBuilder
